[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies] 
solana-program = "2.1.4"
solana-sdk = "2.1.4"
mpl-token-metadata = "5.1.0"
borsh = "1.5.3"
solana-client = "2.1.4" # Ensure this version matches your Solana SDK version


